import { StyleSheet } from 'react-native';

export const quizStyles = StyleSheet.create({
  centerContent: {
    flex: 1,
    justifyContent: 'center',
  },
  card: {
    backgroundColor: '#16141F',
    borderRadius: 20,
    padding: 22,
    borderWidth: 1,
    borderColor: '#2B2737',
  },
  question: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 20,
    lineHeight: 26,
  },
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E1B2A',
    borderRadius: 14,
    paddingVertical: 15,
    paddingHorizontal: 16,
    marginBottom: 10,
    borderWidth: 1.5,
    borderColor: '#2B2737',
  },
  optionSelected: {
    backgroundColor: 'rgba(215,131,216,0.12)',
    borderColor: '#D783D8',
  },
  radio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#3D3850',
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioSelected: {
    borderColor: '#D783D8',
    backgroundColor: '#D783D8',
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioInnerDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FFFFFF',
  },
  optionText: {
    fontSize: 15,
    color: '#A09BAE',
    flex: 1,
  },
  optionTextSelected: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  bottomBar: {
    paddingBottom: 36,
    paddingTop: 16,
  },
  gradientButton: {
    borderRadius: 999,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gradientButtonDisabled: {
    opacity: 0.35,
  },
  continueButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 10,
  },
  chip: {
    backgroundColor: '#1E1B2A',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderWidth: 1.5,
    borderColor: '#2B2737',
  },
  chipSelected: {
    borderColor: '#D783D8',
    backgroundColor: 'rgba(215,131,216,0.12)',
  },
  chipText: {
    fontSize: 14,
    color: '#A09BAE',
    fontWeight: '500',
  },
  chipTextSelected: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  subQuestion: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginTop: 18,
    marginBottom: 12,
  },
});
